package es.upm.dit.isst.ioh.selenium;

// Generated by Selenium IDE
import java.util.Map;

import org.aspectj.lang.annotation.After;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
public class Test1pruebaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        // Configura el path del WebDriver
        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver-win64\\chromedriver.exe");
        // Configura ChromeOptions para aceptar certificados no confiables
        ChromeOptions options = new ChromeOptions();
        options.setAcceptInsecureCerts(true); // Acepta certificados no confiables

        driver = new ChromeDriver(options);
    }
  @After(value = "")
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1prueba() {
    driver.get("http://localhost:5173/");
    driver.manage().window().setSize(new Dimension(1098, 672));
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1ip5wv7-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.id("rolePropietario"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".css-1dovkig")).click();
    {
      WebElement element = driver.findElement(By.id("rolePropietario"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("rolePropietario")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("fullName")).click();
    driver.findElement(By.id("fullName")).sendKeys("teresa cabeza");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("teresa@email.com");
    driver.findElement(By.id("telefono")).click();
    driver.findElement(By.id("telefono")).sendKeys("675443221");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("teresa");
    driver.findElement(By.id("confirmPassword")).click();
    {
      WebElement element = driver.findElement(By.id("registerButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("confirmPassword")).sendKeys("teresa");
    driver.findElement(By.id("registerButton")).click();
    {
      WebElement element = driver.findElement(By.id("roleHuesped"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("registerButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("registerButton")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("email")).sendKeys("teresa@email.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiIconButton-edgeEnd"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("teresa12");
    driver.findElement(By.id("loginButton")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1umw9bq-MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".css-1umw9bq-MuiSvgIcon-root")).click();
    driver.findElement(By.id("password")).click();
    {
      WebElement element = driver.findElement(By.id("loginButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("password")).sendKeys("teresa");
    driver.findElement(By.id("loginButton")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.id("loginButton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1sypljl-MuiButtonBase-root-MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    WebElement element = driver.findElement(By.id("elementId"));
    ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", element);
    element.click();
  }
}
